useragent_bots = [
    r"^(AdsBot|Mediapartners)-Google",
    r"^Googlebot",
    "DoCoMo/2.0 N905i(c100;TB;W24H16) (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)",
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
    "SAMSUNG-SGH-E250/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 UP.Browser/6.2.3.3.c.1.101 (GUI) MMP/2.0 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)",
    "gsa-crawler (Enterprise; S4-E9LJ2B82FJJAA; me@mycompany.com)"
    "^Fast Crawler v X",
    r"^Mozilla/4.0 (compatible; MSIE 5.0; Windows NT)$",
    r"^Mozilla/4.0$",
    "Mozilla/4.05 [en]",
    "Mozilla/5.0 (Slurp/cat; slurp@inktomi.com; http://www.inktomi.com/slurp.html)",
    r"Mozilla/5.0 \(compatible; Yahoo!",
    "Scooter/3.3",
    "Y!J-BSC/1.0 (http://help.yahoo.co.jp/help/jp/blog-search/)",
    "Yahoo! Mindset",
    r"^Yahoo-",
    r"^YahooFeedSeeker",
    r"^YahooSeeker",
    "YahooVideoSearch www.yahoo.com/",
    r"^YahooYSMcm",
    r"^slurp",
    r"^python-requests/",
    r"^Python-urllib/",
    r"^libcurl/",
    r"^Wget/"
]
